create database ecom_project

use ecom_project

select top 20 * from customer_analysis

--total revenue generated by male and female customers

select gender,sum(purchase_amount) as total_revenue,sum(purchase_amount)*100.0/(select sum(purchase_amount) from customer_analysis) as percent_contri from customer_analysis group by gender

--which customer used a discount but still spend more than the average purchase

select customer_id,age,gender,purchase_amount from customer_analysis where purchase_amount>(select avg(purchase_amount) from customer_analysis) and discount_applied='Yes'

--top 5 products with highest avg rating

select top 5 item_purchased,round(avg(review_rating),2) as avg_rating from customer_analysis group by item_purchased order by avg_rating desc

--avg amount between standard and express shipping

select shipping_type, avg(purchase_amount) as revenue from customer_analysis where shipping_type in ('Express','Standard') group by shipping_type

--subscriber and non subscriber analysis

select subscription_status,count(customer_id) as total_customers,avg(purchase_amount) as avg_spend,sum(purchase_amount) as total_revenue from customer_analysis
group by subscription_status
order by total_customers,total_revenue

select * from customer_analysis
--top 5 products with highest discount percent 

select  top 5 item_purchased,sum(purchase_amount),sum(case when discount_applied='Yes' then 1 else 0 end)*100.0/count(*) as discount_rate from customer_analysis
group by item_purchased
order by discount_rate desc

--segment customers into new, returning and loyal segments

select case when previous_purchases=1 then 'new_customer'
			when previous_purchases between 2 and 10 then 'repeat_customer'
			when previous_purchases>10 then 'loyal_customer'
			else 'NA'
			end
			as customer_type, count(customer_id) as customer_count from customer_analysis
group by 
case when previous_purchases=1 then  'new_customer'
			when previous_purchases between 2 and 10 then 'repeat_customer'
			when previous_purchases>10 then 'loyal_customer'
			else 'NA'
			end
;


--top 3 products in each category

with item_count as(
select category,item_purchased, count(customer_id) as item_sold, ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_analysis
group by category,item_purchased
)

select category,item_purchased, item_sold from item_count
where item_rank<=3

select * from customer_analysis
--are repeat customers are also subscriber

select subscription_status,count(customer_id) as customer_count
from customer_analysis
where previous_purchases>5
group by subscription_status

alter table customer_analysis
add age_group varchar(30);

update customer_analysis
set age_group=case
				when age between 0 and 21 then 'Young adult'
				when age between 21 and 35 then 'Adult'
				when age between 35 and 50 then 'Middle-aged'
				when age between 50 and 100 then 'Senior'
				end
--revenue contribution from each age group

select age_group, sum(purchase_amount) as total_revenue, sum(purchase_amount)*100/(select sum(purchase_amount) from customer_analysis) as revenue_contribution 
from customer_analysis
group by age_group

